import {Game,PATH,PADS,TOWERS,ENEMIES,PERKS,MAX_WAVES,towerStats,upgradeCost} from './engine.mjs';
const $=id=>document.getElementById(id), canvas=$('map'),ctx=canvas.getContext('2d');
let game=new Game(),selected=-1,started=false,paused=false,speed=1,aim=false,last=0,uiClock=0,saveClock=0,effects=[],sound=false,audio,overlayKind='',toastTimer;
let records={played:false,wins:0,perfect:false},saved=null;
try{records={...records,...JSON.parse(localStorage.getItem('emberpass-records')||'{}')};let data=JSON.parse(localStorage.getItem('emberpass-save')||'null');if(data&&new Game().restore(data)&&!['won','lost'].includes(data.phase))saved=data;}catch{}
$('continue').hidden=!saved;
function save(){try{localStorage.setItem('emberpass-save',JSON.stringify(game.snapshot()));localStorage.setItem('emberpass-records',JSON.stringify(records));}catch{}}
function toast(text){$('toast').textContent=text;$('toast').style.opacity=1;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.opacity=0,2200)}
function beep(freq=330,length=.07){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=freq;g.gain.setValueAtTime(.04,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+length);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+length)}catch{}}
function hideOverlay(){$('overlay').hidden=true;overlayKind=''}
function start(resume=false){game=new Game();if(resume&&saved)game.restore(saved);started=true;paused=false;selected=-1;effects=[];records.played=true;$('intro').hidden=true;hideOverlay();save();update();beep(440,.12)}
$('begin').onclick=()=>start();$('continue').onclick=()=>start(true);
function modal(kind,html){overlayKind=kind;$('overlay-content').innerHTML=html;$('overlay').hidden=false}
function help(){if(!started)return;paused=true;modal('help','<p class="eyebrow">FIELD MANUAL</p><h2>守望者手冊</h2><p>點選 ＋ 建造格，再選擇防禦塔。連弩適合單體；火砲擅長範圍爆破與穿甲；寒霜可緩速敵軍。點選已建砲塔可升到 3 級，或以 65% 造價出售。</p><p>迎戰前可自由整備；戰鬥中也能建造。每 3 波獲得一次祝福。星落援護有 24 秒冷卻，可打擊指定區域。完成 12 波且城門耐久大於 0 即勝利。</p><p>空白鍵暫停 · 1/2/3 建造 · Esc 取消技能。切換分頁會自動暫停。進度保存在這部裝置。</p><button class="primary" id="close-help">返回防線 →</button>');$('close-help').onclick=()=>{hideOverlay();paused=false;update()};update()}
$('help').onclick=help;$('sound').onclick=()=>{sound=!sound;$('sound').textContent='音效 '+(sound?'開':'關');beep(660)};
$('pause').onclick=()=>{if(!started||overlayKind)return;paused=!paused;update()};$('speed').onclick=()=>{speed=speed===1?2:1;update()};
$('restart').onclick=()=>{if(!started)return;paused=true;modal('restart','<p class="eyebrow">NEW EXPEDITION</p><h2>重新開始守望？</h2><p>本局防線與進度將重置，已獲得的成就會保留。</p><button class="primary" id="confirm-restart">開始新守望 →</button><button id="cancel-restart">返回目前防線</button>');$('confirm-restart').onclick=()=>start();$('cancel-restart').onclick=()=>{hideOverlay();paused=false;update()}};
$('next').onclick=()=>{if(!started||paused)return;if(game.startWave()){save();update();beep(220,.2)}};
$('skill').onclick=()=>{if(!started||paused||game.phase!=='combat'||game.skillCooldown>0)return;aim=!aim;toast(aim?'點選戰場，呼喚星落援護':'已取消技能瞄準');update()};
function build(type){if(selected<0){toast('先點選地圖上的建造格');return}if(paused||!started)return;if(game.build(selected,type)){save();update();beep(520)}else toast(game.gold<TOWERS[type].cost?'金幣不足，消滅敵軍或完成波次可獲得收入':'這個位置無法建造')}
canvas.addEventListener('pointerdown',e=>{if(!started||paused||overlayKind)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*1000/r.width,y=(e.clientY-r.top)*700/r.height;if(aim){if(game.skill(x,y)){aim=false;beep(120,.3);save()}update();return}const p=PADS.map(p=>({...p,d:Math.hypot(x-p.x,y-p.y)})).sort((a,b)=>a.d-b.d)[0];selected=p.d<45?p.id:-1;update()});
document.addEventListener('keydown',e=>{if(e.target.tagName==='BUTTON')return;if(e.code==='Space'){e.preventDefault();$('pause').click()}if(e.key==='Escape'){aim=false;selected=-1;update()}if(['1','2','3'].includes(e.key))build(['arrow','cannon','frost'][+e.key-1]);if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();selected=(selected+(e.key==='ArrowRight'?1:PADS.length-1)+PADS.length)%PADS.length;update()}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&started){paused=true;save();update()}});
let updateSignature='';
function setMarkup(id,html){if($(id).innerHTML!==html)$(id).innerHTML=html}
function update(){const signature=JSON.stringify([game.phase,game.lives,game.gold,game.wave,selected,paused,speed,aim,Math.ceil(game.skillCooldown),game.enemies.length,game.state.queue.length,game.state.kills,game.state.completedWaves,game.towers.map(t=>[t.pad,t.type,t.level]),started,records,overlayKind]);if(signature===updateSignature)return;updateSignature=signature;const t=game.towers.find(t=>t.pad===selected);$('gold').textContent=game.gold;$('lives').textContent=game.lives;$('wave').innerHTML=game.wave+'<small> / 12</small>';$('phase').textContent=paused?'已暫停':({build:'整備防線',combat:'敵軍進攻中',choice:'選擇山谷祝福',won:'山谷已守住',lost:'防線失守'})[game.phase];$('pause').textContent=paused?'繼續':'暫停';$('speed').textContent=speed+'× 速度';$('progress').style.width=game.state.completedWaves/12*100+'%';$('selection-title').textContent=t?TOWERS[t.type].name+' · 等級 '+t.level:selected<0?'選擇建造位置':'建造格 '+(selected+1);$('selection-sub').textContent=t?'升級火力，或調整防線配置':selected<0?'點選地圖上的發光建造格':'為這個位置選擇防禦塔';$('tower-list').hidden=!!t;$('tower-actions').hidden=!t;
setMarkup('tower-list',Object.entries(TOWERS).map(([type,d],i)=>'<button class="tower-card" data-type="'+type+'" '+(game.gold<d.cost||!started||paused||!game.canManage()?'disabled':'')+'><span class="tower-icon">'+['➶','◉','❄'][i]+'</span><span class="tower-copy"><b>'+d.name+'</b><small>'+d.description+'</small></span><b class="cost">◈ '+d.cost+'</b></button>').join(''));document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>build(b.dataset.type));
if(t){let st=towerStats(t,game.perks);setMarkup('tower-actions','<div>傷害 <b>'+Math.round(st.damage)+'</b>　射程 <b>'+Math.round(st.range)+'</b><br>射擊間隔 '+st.interval.toFixed(2)+' 秒</div><button id="upgrade" '+(t.level>=3||game.gold<upgradeCost(t)||paused||!game.canManage()?'disabled':'')+'>'+(t.level>=3?'已達最高等級':'升級至 Lv.'+(t.level+1)+' · ◈ '+upgradeCost(t))+'</button><button id="sell" '+(paused||!game.canManage()?'disabled':'')+'>出售 · 回收 ◈ '+Math.floor(t.invested*.65)+'</button>');$('upgrade').onclick=()=>{if(game.upgrade(selected)){beep(680);save();update()}};$('sell').onclick=()=>{if(game.sell(selected)){save();update()}}}
$('skill').disabled=game.phase!=='combat'||game.skillCooldown>0||paused;$('skill').textContent=aim?'取消瞄準':game.skillCooldown>0?Math.ceil(game.skillCooldown)+' 秒':'準備就緒';$('next').disabled=game.phase!=='build'||paused||!started;$('next').innerHTML=(game.phase==='combat'?'防守進行中':game.wave===12?'守望結束':'迎接第 '+(game.wave+1)+' 波')+' <span>→</span>';$('status').textContent=game.phase==='combat'?'場上敵軍 '+game.enemies.length+' · 待入場 '+game.state.queue.length+' · 已擊退 '+game.state.kills:game.phase==='build'?'下一波：'+(game.wave===11?'熔火巨像率領總攻':game.wave>=3?'鐵甲與快速敵軍混編':'敵軍正在集結')+'。整備完成後開始。':game.phase==='choice'?'選擇一項祝福，強化本局防線。':game.phase==='won'?'12 波全部守住。山谷會記得你的名字。':'調整塔的搭配，再挑戰一次。';$('hint').textContent=aim?'星落瞄準中：點選戰場施放':selected>=0?'已選擇建造格 '+(selected+1)+' · 地面圓圈為實際射程':'點選 ＋ 建造防禦 · 點選砲塔升級';$('achievements').innerHTML='<span class="'+(records.played?'earned':'')+'">'+(records.played?'◆':'◇')+' 初次守望</span><span class="'+(records.wins?'earned':'')+'">'+(records.wins?'◆':'◇')+' 山谷守護者 '+(records.wins||'')+'</span><span class="'+(records.perfect?'earned':'')+'">'+(records.perfect?'◆':'◇')+' 完美防線</span>';
if(started&&game.phase==='choice'&&overlayKind!=='choice'){modal('choice','<p class="eyebrow">CHOOSE YOUR BLESSING</p><h2>山谷的回應</h2><p>第 '+game.wave+' 波已守住。選擇一項祝福，本局持續生效。</p>'+PERKS.map(p=>'<button class="perk" data-perk="'+p.id+'"><b>✦ '+p.name+'</b><small>'+p.description+'</small></button>').join(''));document.querySelectorAll('[data-perk]').forEach(b=>b.onclick=()=>{if(game.choosePerk(b.dataset.perk)){hideOverlay();save();update()}})}
if(started&&['won','lost'].includes(game.phase)&&overlayKind!=='result'){modal('result','<p class="eyebrow">'+(game.phase==='won'?'THE VALLEY REMEMBERS':'ANOTHER DAWN AWAITS')+'</p><h2>'+(game.phase==='won'?'曙光，屬於守望者。':'防線失守，守望不息。')+'</h2><p>完成 '+game.state.completedWaves+' / 12 波 · 擊退 '+game.state.kills+' 名敵軍<br>城門耐久 '+game.lives+' / 20</p><p>'+(game.phase==='won'?'你的戰術讓山谷迎來新的一天。試試更少的防禦塔，挑戰自己的策略。':'先在彎道內側建立連弩與火砲，再加入寒霜塔延長輸出時間。')+'</p><button class="primary" id="replay">再展開一次守望 →</button>');$('replay').onclick=()=>start()}}
// Original immediate-mode polygon artwork: no downloaded models or textures.
function poly(points,color){ctx.fillStyle=color;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fill()}
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill()}
function box(x,y,w,d,h,top,left,right){poly([[x-w,y-d],[x,y-d*2],[x+w,y-d],[x,y]],top);poly([[x-w,y-d],[x,y],[x,y+h],[x-w,y-d+h]],left);poly([[x,y],[x+w,y-d],[x+w,y-d+h],[x,y+h]],right)}
function tree(x,y,s=1){ellipse(x+8*s,y+6*s,20*s,8*s,'#173d3940');box(x,y-9*s,3*s,2*s,18*s,'#806651','#4d5143','#354b3e');poly([[x,y-83*s],[x-25*s,y-22*s],[x+24*s,y-22*s]],'#357161');poly([[x,y-83*s],[x,y-22*s],[x+24*s,y-22*s]],'#204e49');poly([[x-18*s,y-38*s],[x,y-93*s],[x,y-36*s]],'#477f62')}
function rock(x,y,s){poly([[x-28*s,y],[x-19*s,y-23*s],[x+7*s,y-35*s],[x+28*s,y-13*s],[x+20*s,y+8*s]],'#6b897a');poly([[x-19*s,y-23*s],[x+7*s,y-35*s],[x+5*s,y-8*s],[x-28*s,y]],'#8fa18c');poly([[x+5*s,y-8*s],[x+28*s,y-13*s],[x+20*s,y+8*s],[x-28*s,y]],'#45665e')}
const scenery=[];let seed=76543;function rng(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}function roadDistance(x,y){let min=1e9;for(let i=1;i<PATH.length;i++){let a=PATH[i-1],b=PATH[i],dx=b.x-a.x,dy=b.y-a.y,t=Math.max(0,Math.min(1,((x-a.x)*dx+(y-a.y)*dy)/(dx*dx+dy*dy)));min=Math.min(min,Math.hypot(x-a.x-t*dx,y-a.y-t*dy))}return min}for(let i=0;i<120;i++){let x=rng()*1000,y=65+rng()*610;if(roadDistance(x,y)>72&&PADS.every(p=>Math.hypot(x-p.x,y-p.y)>60))scenery.push({x,y,s:.55+rng()*.5,type:rng()>.25?'tree':'rock'})}
function pathStroke(width,color){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineJoin='round';ctx.lineCap='round';ctx.beginPath();PATH.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()}
function tower(p,t,time){ellipse(p.x+8,p.y+8,28,12,'#143c384d');box(p.x,p.y-1,25,13,9,'#b8bda1','#587c71','#365d56');box(p.x,p.y-17,15,9,21,'#6caaa6','#3a777c','#2a5965');if(t.type==='arrow'){box(p.x,p.y-35,19,10,13,'#d5bc77','#8b885d','#686c4e');ctx.save();ctx.translate(p.x,p.y-37);ctx.rotate(t.angle||0);ctx.strokeStyle='#dcc793';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(-20,0);ctx.lineTo(22,0);ctx.stroke();ctx.strokeStyle='#486570';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(5,-16);ctx.lineTo(13,0);ctx.lineTo(5,16);ctx.stroke();ctx.restore()}else if(t.type==='cannon'){ellipse(p.x,p.y-26,20,13,'#45606a');ctx.save();ctx.translate(p.x,p.y-29);ctx.rotate(t.angle||0);ctx.fillStyle='#283e49';ctx.fillRect(-9,-9,36,18);ctx.fillStyle='#82939a';ctx.fillRect(17,-11,11,22);ctx.fillStyle='#24313e';ctx.fillRect(25,-7,3,14);ctx.restore()}else{poly([[p.x,p.y-67],[p.x-15,p.y-39],[p.x,p.y-21],[p.x+15,p.y-39]],'#a7e4df');poly([[p.x,p.y-67],[p.x,p.y-21],[p.x+15,p.y-39]],'#60aebc');ellipse(p.x,p.y-23,23,6,'#9ce7d130')}for(let i=0;i<t.level;i++)ellipse(p.x-7+(i*7),p.y+11,2,2,'#f1d898')}
function enemy(e,time){const def=ENEMIES[e.type],boss=e.type==='boss',s=boss?2.0:e.type==='swarm'?.62:1;let x=e.x,y=e.y,bob=Math.sin(time*9+e.id)*1.3;ellipse(x+5,y+4,12*s,5*s,'#203d3555');ctx.save();ctx.translate(x,y+bob);ctx.scale(s,s);const color=e.slow>0?'#80ccd5':e.type==='armored'?'#967f87':e.type==='fast'?'#d6a267':'#ce705a';box(0,-13,9,5,12,color,'#9d4946','#7b3e44');box(0,-25,6,4,10,boss?'#e6b87b':'#e7b191','#ba795f','#99584f');poly([[-8,-20],[0,-32],[9,-21]],e.type==='armored'?'#5f6374':'#ba554d');ctx.strokeStyle='#403e3e';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-5,-1);ctx.lineTo(-6+Math.sin(time*10+e.id)*3,5);ctx.moveTo(5,-1);ctx.lineTo(6-Math.sin(time*10+e.id)*3,5);ctx.stroke();if(boss){poly([[-12,-28],[-17,-42],[-5,-31]],'#e6ce89');poly([[12,-28],[17,-42],[5,-31]],'#e6ce89')}ctx.restore();if(e.hp<e.maxHp||boss){ctx.fillStyle='#3b343a';ctx.fillRect(x-14*s,y-38*s,28*s,3);ctx.fillStyle=e.slow?'#a7e8df':'#efb88d';ctx.fillRect(x-14*s,y-38*s,28*s*e.hp/e.maxHp,3)}}
function draw(time){ctx.clearRect(0,0,1000,700);ctx.fillStyle='#4d816b';ctx.fillRect(0,0,1000,700);poly([[0,0],[360,0],[220,145],[0,115]],'#60896f');poly([[410,0],[1000,0],[1000,305],[820,210],[640,60]],'#638b71');poly([[0,480],[240,415],[410,590],[370,700],[0,700]],'#3d7367');poly([[700,350],[1000,260],[1000,700],[810,700]],'#588570');poly([[0,655],[145,620],[270,700],[0,700]],'#35645c');for(let i=0;i<30;i++){const x=(i*173)%1000,y=(i*97)%700;poly([[x,y],[x+45,y+7],[x+25,y+15]],'#8ca3800a')}pathStroke(76,'#3c695649');pathStroke(65,'#9c9f77');pathStroke(56,'#c5bf94');pathStroke(45,'#d0c69d');ctx.setLineDash([2,38]);pathStroke(2,'#afaa8233');ctx.setLineDash([]);
// Low-poly stone ridges and the protected city gate.
rock(385,80,1.4);rock(400,105,.8);rock(45,548,1.4);rock(956,630,1.2);ctx.fillStyle='#244a4344';ctx.fillRect(942,461,58,80);box(971,473,28,15,71,'#bfbaa0','#708675','#496b60');box(950,454,11,6,65,'#c6c4a5','#7c9080','#4e7467');box(992,454,11,6,65,'#c6c4a5','#7c9080','#4e7467');poly([[954,483],[979,470],[979,526],[954,538]],'#2f514d');poly([[961,434],[961,399],[987,410],[961,419]],'#6295a8');ctx.strokeStyle='#dbd4b5';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(961,444);ctx.lineTo(961,394);ctx.stroke();
if(selected>=0){const t=game.towers.find(t=>t.pad===selected),p=PADS[selected];ellipse(p.x,p.y,t?towerStats(t,game.perks).range:190,t?towerStats(t,game.perks).range:190,'#d6e8bc10');ctx.strokeStyle='#e8d49c77';ctx.lineWidth=1.5;ctx.setLineDash([6,5]);ctx.beginPath();ctx.arc(p.x,p.y,t?towerStats(t,game.perks).range:190,0,Math.PI*2);ctx.stroke();ctx.setLineDash([])}
for(const p of PADS){if(game.towers.some(t=>t.pad===p.id))continue;ellipse(p.x,p.y+5,28,15,'#234d4055');poly([[p.x-26,p.y-9],[p.x,p.y-23],[p.x+26,p.y-9],[p.x,p.y+6]],selected===p.id?'#c6ca9d':'#9da77c');ctx.strokeStyle=selected===p.id?'#fff0b7':'#d8ddb6';ctx.lineWidth=2;ctx.setLineDash([7,5]);ctx.beginPath();ctx.ellipse(p.x,p.y-6,29,19,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.font='24px sans-serif';ctx.textAlign='center';ctx.fillStyle='#f2e7b9';ctx.fillText('+',p.x,p.y+1)}
const objects=[...scenery.map(o=>({...o,draw:()=>o.type==='tree'?tree(o.x,o.y,o.s):rock(o.x,o.y,o.s)})),...game.towers.map(t=>({y:PADS[t.pad].y,draw:()=>tower(PADS[t.pad],t,time)})),...game.enemies.map(e=>({y:e.y,draw:()=>enemy(e,time)}))];objects.sort((a,b)=>a.y-b.y).forEach(o=>o.draw());
// Blue watch captain, an original stationary field guardian.
ellipse(909,554,14,6,'#21443855');box(906,533,9,5,17,'#76aebe','#356e85','#285067');box(906,517,6,4,9,'#e0c296','#b99975','#90765e');poly([[897,535],[904,551],[917,541],[911,522]],'#477e9e');ctx.strokeStyle='#c6d4c1';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(920,515);ctx.lineTo(920,551);ctx.stroke();
for(const e of effects){const a=Math.max(0,1-e.age/e.life);ctx.globalAlpha=a;if(e.kind==='shot'){ctx.strokeStyle=e.color;ctx.lineWidth=e.type==='cannon'?5:2;ctx.beginPath();ctx.moveTo(e.x,e.y-28);ctx.lineTo(e.targetX,e.targetY-15);ctx.stroke();ellipse(e.targetX,e.targetY-10,e.type==='cannon'?17:6,e.type==='cannon'?11:6,e.color)}if(e.kind==='kill'){ctx.font='bold 12px sans-serif';ctx.fillStyle='#f7dfa6';ctx.textAlign='center';ctx.fillText('+'+e.reward,e.x,e.y-20-e.age*25)}if(e.kind==='skill'){ctx.strokeStyle='#c9fff0';ctx.lineWidth=4;ctx.beginPath();ctx.arc(e.x,e.y,125*(1-a*.8),0,Math.PI*2);ctx.stroke();for(let i=0;i<6;i++){ctx.beginPath();ctx.moveTo(e.x+Math.cos(i)*80,e.y-160);ctx.lineTo(e.x+Math.cos(i)*80,e.y+Math.sin(i)*70);ctx.stroke()}}ctx.globalAlpha=1}
const grad=ctx.createRadialGradient(500,320,220,500,320,650);grad.addColorStop(0,'#0f303000');grad.addColorStop(1,'#0a292c66');ctx.fillStyle=grad;ctx.fillRect(0,0,1000,700);if(paused&&started&&!overlayKind){ctx.fillStyle='#15343b77';ctx.fillRect(0,0,1000,700);ctx.fillStyle='#f3e7c1';ctx.textAlign='center';ctx.font='28px sans-serif';ctx.fillText('守望暫停',500,330);ctx.font='13px sans-serif';ctx.fillText('按「繼續」或空白鍵返回戰場',500,359)}}
function frame(timestamp){const dt=Math.min((timestamp-last)/1000,.08)||0;last=timestamp;if(started&&!paused&&!overlayKind){game.step(dt*speed);for(const e of game.drainEvents()){if(e.type==='shot')effects.push({...e,kind:'shot',type:e.towerType,color:TOWERS[game.towers.find(t=>t.pad===e.pad)?.type||'arrow'].color,age:0,life:.16});if(e.type==='kill')effects.push({...e,kind:'kill',age:0,life:.65});if(e.type==='skill')effects.push({...e,kind:'skill',age:0,life:.7});if(e.type==='waveComplete'){toast('第 '+e.wave+' 波守住！補給 +'+e.bonus);save()}if(e.type==='won'){records.wins++;if(game.lives===20)records.perfect=true;save()}if(e.type==='lost')save()}saveClock+=dt;if(saveClock>2){saveClock=0;save()}}effects=effects.filter(e=>(e.age+=dt)<e.life);draw(timestamp/1000);uiClock+=dt;if(uiClock>.15){uiClock=0;update()}requestAnimationFrame(frame)}
update();requestAnimationFrame(frame);
