/** Deterministic, dependency-free Emberpass rules. Distances use a 1000 × 700 board. */
export const PATH = Object.freeze([{x:-25,y:145},{x:205,y:145},{x:205,y:355},{x:455,y:355},{x:455,y:160},{x:720,y:160},{x:720,y:505},{x:1005,y:505}].map(Object.freeze));
export const PADS = Object.freeze([{x:120,y:245},{x:300,y:245},{x:320,y:455},{x:545,y:275},{x:600,y:75},{x:820,y:255},{x:615,y:440},{x:815,y:605},{x:905,y:410},{x:105,y:65},{x:540,y:535},{x:800,y:65}].map((p,id)=>Object.freeze({...p,id})));
export const TOWERS = Object.freeze({arrow:Object.freeze({name:'連弩塔',cost:90,damage:19,range:190,interval:0.62,color:'#ffd479',description:'快速射擊，穩定單體傷害'}),cannon:Object.freeze({name:'火砲塔',cost:135,damage:39,range:180,interval:1.65,splash:78,color:'#ff946d',description:'範圍爆破，克制密集敵群'}),frost:Object.freeze({name:'寒霜塔',cost:105,damage:10,range:170,interval:1.05,slow:0.48,color:'#83ddf4',description:'冰霜緩速，延長防線火力'})});
export const ENEMIES = Object.freeze({grunt:Object.freeze({name:'灰燼兵',hp:68,speed:61,reward:9,armor:0,color:'#e89669'}),fast:Object.freeze({name:'疾行獸',hp:49,speed:103,reward:10,armor:0,color:'#e7c563'}),swarm:Object.freeze({name:'火花蟲',hp:33,speed:76,reward:6,armor:0,color:'#db847b'}),armored:Object.freeze({name:'鐵甲衛',hp:170,speed:43,reward:16,armor:0.36,color:'#9e9aad'}),boss:Object.freeze({name:'熔火巨像',hp:2800,speed:27,reward:200,armor:0.22,color:'#ef6a56'})});
export const PERKS = Object.freeze([{id:'damage',name:'淬火鋒刃',description:'所有防禦塔傷害 +15%'},{id:'range',name:'鷹眼瞭望',description:'所有防禦塔射程 +12%'},{id:'gold',name:'王國補給',description:'立即獲得 150 金幣'}]);
export const MAX_WAVES = 12;
const lengths=PATH.slice(1).map((p,i)=>Math.hypot(p.x-PATH[i].x,p.y-PATH[i].y));
export const PATH_LENGTH=lengths.reduce((a,b)=>a+b,0);
const finite=n=>typeof n==='number'&&Number.isFinite(n);
const integer=n=>Number.isInteger(n);
export function pointAt(progress){let d=Math.max(0,progress);for(let i=0;i<lengths.length;i++){if(d<=lengths[i]){const t=d/lengths[i];return {x:PATH[i].x+(PATH[i+1].x-PATH[i].x)*t,y:PATH[i].y+(PATH[i+1].y-PATH[i].y)*t};}d-=lengths[i];}return {...PATH.at(-1)};}
export function upgradeCost(tower){return tower&&tower.level<3?Math.round(TOWERS[tower.type].cost*(tower.level===1?0.85:1.2)):0;}
export function towerStats(tower,perks={damage:0,range:0}){const def=TOWERS[tower.type];return {...def,damage:def.damage*(1+0.72*(tower.level-1))*(1+0.15*(perks.damage||0)),range:def.range*(1+0.08*(tower.level-1))*(1+0.12*(perks.range||0)),interval:def.interval/(1+0.10*(tower.level-1))};}
function waveQueue(n){const result=[];const count=7+n*2;for(let i=0;i<count;i++){let type='grunt';if(n>=2&&i%4===1)type='fast';if(n>=3&&i%5===2)type='swarm';if(n>=4&&i%5===3)type='armored';result.push(type);if(n>=6&&type==='swarm')result.push('swarm');}if(n===12)result.splice(Math.floor(result.length/2),0,'boss');return result;}
export class Game {
 constructor(){this.events=[];this.state={version:1,phase:'build',wave:0,gold:315,lives:20,towers:[],enemies:[],queue:[],spawnTimer:0,skillCooldown:0,time:0,nextId:1,kills:0,earned:0,perks:{damage:0,range:0},completedWaves:0};}
 get phase(){return this.state.phase;} get gold(){return this.state.gold;} get lives(){return this.state.lives;} get wave(){return this.state.wave;} get towers(){return this.state.towers;} get enemies(){return this.state.enemies;} get skillCooldown(){return this.state.skillCooldown;} get perks(){return this.state.perks;}
 emit(type,data={}){this.events.push({...data,type});if(this.events.length>100)this.events.shift();}
 drainEvents(){return this.events.splice(0);}
 canManage(){return this.phase==='build'||this.phase==='combat';}
 build(pad,type){const s=this.state;if(!this.canManage()||!integer(pad)||!PADS[pad]||!Object.hasOwn(TOWERS,type)||s.towers.some(t=>t.pad===pad)||s.gold<TOWERS[type].cost)return false;const cost=TOWERS[type].cost;s.gold-=cost;s.towers.push({pad,type,level:1,cooldown:0,invested:cost,angle:0});this.emit('build',{pad});return true;}
 upgrade(pad){const s=this.state,t=s.towers.find(t=>t.pad===pad),cost=upgradeCost(t);if(!this.canManage()||!t||!cost||s.gold<cost)return false;s.gold-=cost;t.invested+=cost;t.level++;this.emit('upgrade',{pad});return true;}
 sell(pad){const s=this.state,index=s.towers.findIndex(t=>t.pad===pad);if(!this.canManage()||index<0)return false;const t=s.towers[index];s.gold+=Math.floor(t.invested*0.65);s.towers.splice(index,1);this.emit('sell',{pad});return true;}
 startWave(){const s=this.state;if(s.phase!=='build'||s.wave>=MAX_WAVES)return false;s.wave++;s.phase='combat';s.queue=waveQueue(s.wave);s.spawnTimer=0;this.emit('wave',{wave:s.wave});return true;}
 choosePerk(id){const s=this.state;if(s.phase!=='choice'||!PERKS.some(p=>p.id===id))return false;if(id==='gold')s.gold+=150;else s.perks[id]++;s.phase='build';this.emit('perk',{id});return true;}
 skill(x,y){const s=this.state;if(s.phase!=='combat'||s.skillCooldown>0||!finite(x)||!finite(y)||x<0||x>1000||y<0||y>700)return false;s.skillCooldown=24;for(const e of s.enemies){if(Math.hypot(e.x-x,e.y-y)<=125){e.hp-=155;e.slow=2.5;}}this.emit('skill',{x,y,radius:125});this.cleanup();return true;}
 cleanup(){const s=this.state;for(const e of s.enemies){if(e.hp<=0){const reward=ENEMIES[e.type].reward;s.gold+=reward;s.earned+=reward;s.kills++;this.emit('kill',{x:e.x,y:e.y,reward,enemyType:e.type});}}s.enemies=s.enemies.filter(e=>e.hp>0);}
 step(dt){if(!finite(dt)||dt<=0)return;let remain=Math.min(dt,5);while(remain>0){const tick=Math.min(1/30,remain);this.tick(tick);remain-=tick;}}
 tick(dt){const s=this.state;if(s.phase==='won'||s.phase==='lost')return;s.time+=dt;s.skillCooldown=Math.max(0,s.skillCooldown-dt);if(s.phase!=='combat')return;s.spawnTimer-=dt;if(s.queue.length&&s.spawnTimer<=0){const type=s.queue.shift(),def=ENEMIES[type],scale=1+0.135*(s.wave-1),hp=def.hp*scale;const e={id:s.nextId++,type,hp,maxHp:hp,progress:0,slow:0,...pointAt(0)};s.enemies.push(e);s.spawnTimer+=type==='swarm'?0.39:Math.max(0.49,1.03-s.wave*0.026);this.emit('spawn',{id:e.id});}
 for(const t of s.towers){t.cooldown-=dt;if(t.cooldown>0)continue;const p=PADS[t.pad],st=towerStats(t,s.perks);const candidates=s.enemies.filter(e=>e.hp>0&&Math.hypot(e.x-p.x,e.y-p.y)<=st.range);const target=candidates.sort((a,b)=>b.progress-a.progress||a.id-b.id)[0];if(!target){t.cooldown=0;continue;}t.cooldown+=st.interval;t.angle=Math.atan2(target.y-p.y,target.x-p.x);const targets=st.splash?s.enemies.filter(e=>e.hp>0&&Math.hypot(e.x-target.x,e.y-target.y)<=st.splash):[target];for(const e of targets){e.hp-=st.damage*(1-ENEMIES[e.type].armor*(t.type==='cannon'?0.4:1));if(st.slow)e.slow=1.65;}this.emit('shot',{pad:t.pad,towerType:t.type,x:p.x,y:p.y,targetX:target.x,targetY:target.y});}
 this.cleanup();for(const e of s.enemies){e.slow=Math.max(0,e.slow-dt);e.progress+=ENEMIES[e.type].speed*(e.slow>0?0.48:1)*dt;Object.assign(e,pointAt(e.progress));}const escaped=s.enemies.filter(e=>e.progress>=PATH_LENGTH);for(const e of escaped){s.lives=Math.max(0,s.lives-(e.type==='boss'?10:1));this.emit('leak',{x:e.x,y:e.y});}s.enemies=s.enemies.filter(e=>e.progress<PATH_LENGTH);if(s.lives<=0){s.phase='lost';this.emit('lost');return;}if(!s.queue.length&&!s.enemies.length){s.completedWaves=s.wave;const bonus=45+s.wave*6;s.gold+=bonus;s.earned+=bonus;this.emit('waveComplete',{wave:s.wave,bonus});s.phase=s.wave===MAX_WAVES?'won':s.wave%3===0?'choice':'build';if(s.phase==='won')this.emit('won');}}
 snapshot(){return JSON.parse(JSON.stringify(this.state));}
 restore(data){try{const s=JSON.parse(JSON.stringify(data));if(!s||s.version!==1||!['build','combat','choice','won','lost'].includes(s.phase)||!integer(s.wave)||s.wave<0||s.wave>12||!integer(s.gold)||s.gold<0||!integer(s.lives)||s.lives<0||s.lives>20||!Array.isArray(s.towers)||s.towers.length>PADS.length||!Array.isArray(s.enemies)||s.enemies.length>1000||!Array.isArray(s.queue)||s.queue.length>1000||!s.queue.every(x=>Object.hasOwn(ENEMIES,x)))return false;
 const nums=['spawnTimer','skillCooldown','time','nextId','kills','earned','completedWaves'];if(!nums.every(k=>finite(s[k]))||s.skillCooldown<0||s.skillCooldown>24||s.time<0||!integer(s.nextId)||s.nextId<1||!integer(s.kills)||s.kills<0||!integer(s.earned)||s.earned<0||!integer(s.completedWaves)||s.completedWaves<0||s.completedWaves>s.wave||!s.perks||!['damage','range'].every(k=>integer(s.perks[k])&&s.perks[k]>=0&&s.perks[k]<=3)||s.perks.damage+s.perks.range>3)return false;
 const pads=new Set();for(const t of s.towers){if(!integer(t.pad)||!PADS[t.pad]||pads.has(t.pad)||!Object.hasOwn(TOWERS,t.type)||!integer(t.level)||t.level<1||t.level>3||!finite(t.cooldown)||!finite(t.angle)||!integer(t.invested)||t.invested!==TOWERS[t.type].cost+(t.level>=2?Math.round(TOWERS[t.type].cost*0.85):0)+(t.level>=3?Math.round(TOWERS[t.type].cost*1.2):0)||t.cooldown<0||t.cooldown>TOWERS[t.type].interval)return false;pads.add(t.pad);}
 const ids=new Set();for(const e of s.enemies){if(!Object.hasOwn(ENEMIES,e.type)||!integer(e.id)||e.id<1||e.id>=s.nextId||ids.has(e.id)||!['hp','maxHp','progress','slow','x','y'].every(k=>finite(e[k]))||e.hp<=0||e.hp>e.maxHp||e.progress<0||e.progress>=PATH_LENGTH||e.slow<0)return false;ids.add(e.id);const p=pointAt(e.progress);if(Math.abs(e.x-p.x)>0.001||Math.abs(e.y-p.y)>0.001)return false;}
 if((s.phase==='won'&&(s.wave!==12||s.completedWaves!==12||s.lives===0))||(s.phase==='lost'&&s.lives!==0)||(s.phase!=='lost'&&s.lives===0)||(s.phase==='combat'&&(s.wave===0||s.completedWaves!==s.wave-1))||(s.phase==='choice'&&(![3,6,9].includes(s.wave)||s.completedWaves!==s.wave))||(['build','choice','won'].includes(s.phase)&&(s.enemies.length||s.queue.length))||(s.phase==='build'&&(s.wave>=12||s.completedWaves!==s.wave)))return false;
 this.state=s;this.events=[];return true;}catch{return false;}}
}
